version: '3'

volumes:
  pg_data_foodgram:
  static:
  media:


services:

  db_foodgram:

    image: postgres:13.10

    env_file: .env

    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data

  backend_foodgram:
    image: aleklandra/foodgram_backend
    env_file: .env

    volumes:
      - static:/backend_static
      - media:/app/media

    depends_on:
      - db_foodgram
  
  frontend:
    env_file: .env
    image: aleklandra/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  gateway:
    image: aleklandra/foodgram_gateway

    volumes:
      - static:/staticfiles/
      - media:/media:ro

    ports:
      - 8000:80