# Generated by Django 3.2 on 2024-08-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_userrecipelists_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecipelists',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrecipelists',
            name='is_in_shopping_cart',
            field=models.BooleanField(default=False),
        ),
    ]
