# Generated by Django 3.2 on 2024-09-14 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_alter_ingredientrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='users',
            field=models.ManyToManyField(related_name='user_lists', through='recipes.UserRecipeLists', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
