# Generated by Django 3.2 on 2024-09-05 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20240826_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='users',
            field=models.ManyToManyField(related_name='users', through='recipes.UserRecipeLists', to=settings.AUTH_USER_MODEL),
        ),
    ]
