# Generated by Django 3.2 on 2024-09-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_ingredientrecipe_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'ordering': ('ingredient',), 'verbose_name': 'Ингредиент рецепта', 'verbose_name_plural': 'Ингредиенты рецепта'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'ordering': ('tag',), 'verbose_name': 'Тег рецепта', 'verbose_name_plural': 'Теги рецепта'},
        ),
    ]
