# Generated by Django 3.2 on 2024-09-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'ordering': ('sub_id',), 'verbose_name': 'Подпика', 'verbose_name_plural': 'Подписки'},
        ),
    ]
